
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
    - git config credential.helper "store --file=.git/credentials"; echo "https://${github_token}:@github.com" > .git/credentials 2>/dev/null
    - git config --global user.email "travis@build.ci"
    - git config --global user.name "Travis CI build agent"
script:
  - yarn test
  - yarn run deploy